const mongoose = require("mongoose");

const matchSchema = new mongoose.Schema({
  awayTeam: { type: String },
  homeTeam: { type: String },
  awayTeamScore: { type: String },
  homeTeamScore: { type: String },
  homeTeamColor: { type: String },
  awayTeamColor: { type: String },
  referee: { type: String },
  arena: { type: String },
  matchDate: { type: Date },
  matchTime: { type: String },
  awayTeamLogo: { type: String },
  homeTeamLogo: { type: String },
  homeTeamPts: {
    first_pts: { type: Number },
    second_pts: { type: Number },
    third_pts: { type: Number },
    fourth_pts: { type: Number },
  },
  awayTeamPts: {
    first_pts_a: { type: Number },
    second_pts_a: { type: Number },
    third_pts_a: { type: Number },
    fourth_pts_a: { type: Number },
  },
  awayTeamStats: {
    playerName: { type: String },
    playerNumber: { type: Number },
    minutesPlayed: { type: Number },
    two_fgm: { type: Number },
    two_fga: { type: Number },
    two_fgp: { type: Number },
    three_fgm: { type: Number },
    three_fga: { type: Number },
    three_fgp: { type: Number },
    ftm: { type: Number },
    fta: { type: Number },
    ftp: { type: Number },
    reb: { type: Number },
    ass: { type: Number },
    fouls: { type: Number },
    tov: { type: Number },
    blocks: { type: Number },
    pts: { type: Number },
  },
  homeTeamStats: {
    playerName: { type: String },
    playerNumber: { type: Number },
    minutesPlayed: { type: Number },
    two_fgm: { type: Number },
    two_fga: { type: Number },
    two_fgp: { type: Number },
    three_fgm: { type: Number },
    three_fga: { type: Number },
    three_fgp: { type: Number },
    ftm: { type: Number },
    fta: { type: Number },
    ftp: { type: Number },
    reb: { type: Number },
    ass: { type: Number },
    fouls: { type: Number },
    tov: { type: Number },
    blocks: { type: Number },
    pts: { type: Number },
  },
});

module.exports = mongoose.model("matches", matchSchema);
